#!/bin/sh

DIR="$(cd "$(dirname "${0}")" && pwd)"
GIT_HOOKS="$DIR/hooks/git"

git config pull.ff only

# GIT HOOKS PATH
git config core.hooksPath "$GIT_HOOKS"
echo "Git hooks: $GIT_HOOKS"

sudo sysctl net.ipv4.ip_unprivileged_port_start=80

if ! command -v python3 &> /dev/null; then
	echo "Please, install python3 before continue"
	exit 1
fi
