version: '3.9'

volumes:
  postgres:
    name: 'bookstore-postgres'
#  localstack:
#    name: 'bookstore-mini-cloud'

networks:
  app:

services:
  postgres:
    image: postgres:16.1
    restart: always
    hostname: postgres-srv
    env_file:
      - ./envs/.env.postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    networks:
      app:

  adminer:
    image: adminer:latest
    restart: always
    hostname: adm-srv
    environment:
      ADMINER_DEFAULT_SERVER: postgres-srv
    ports:
      - '8080:8080'
    networks:
      app:

  pgamin:
    image: dpage/pgadmin4:8.1
    restart: always
    hostname: pgadmin-srv
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
      app:

#  localstack:
#    image: localstack/localstack:3.0.2
#    hostname: localstack-srv
#    restart: always
#    environment:
#      DEBUG: 1
#      PERSISTENCE: 1
#      LS_LOG: debug
#      SERVICES: "s3,sqs,rds"
#    volumes:
#      - localstack:/var/lib/localstack
#    ports:
#      - "4566:4566"
#      - "4510-4559:4510-4559"
#    networks:
#      app:
