version: '3.9'

services:
#  auth:
#    build:
#      context: ../auth
#      dockerfile: Dockerfile
#    restart: always
#    hostname: auth-srv
#    env_file:
#      - ./envs/.env.auth
#    expose:
#      - '3000'
#    ports:
#      - '3000:3000'
#    volumes:
#      - auth
#    networks:
#      app:

  postgres:
    image: postgres:latest
    restart: always
    hostname: postgres-srv
    environment:
      POSTGRES_MULTIPLE_DATABASES: bookstore:identity:postgres,bookstore:iam:postgres,bookstore:store:postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    networks:
      app:

  adminer:
    image: adminer:latest
    restart: always
    hostname: adm-srv
    environment:
      ADMINER_DEFAULT_SERVER: postgres-srv
    ports:
      - '8080:8080'
    expose:
      - '8080'
    networks:
      app:

volumes:
  postgres:
    name: 'bookstore-postgres'
  auth:
    name: 'bookstore-auth'
  library:
    name: 'bookstore-library'

networks:
  app:
