#!/bin/bash

FULL_NAME="${1:-server}"
NAME=$(echo "$FULL_NAME" | tr '.' ' ' | awk '{print $1}')

CHAIN="$NAME.chain.pem"
CRT="$NAME.crt"
KEY="$NAME.key"

openssl req -x509 -out "$CRT" -keyout "$KEY" \
  -newkey rsa:2048 -nodes -sha256 \
  -subj "/C=/ST=/L=/O=/CN=localhost"

openssl req -x509 -newkey rsa:4096 -keyout ${KEY} -out ${CRT} -days 365000 -nodes -subj "/CN=localhost"

cat "$CRT" "$KEY" > "$CHAIN"

echo "Arquivos criados:"
echo "$CHAIN"
echo "$CRT"
echo "$KEY"

chmod "${2:-777}" "$CHAIN" "$CRT" "$KEY"
