#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${0}")" && pwd)"
BASE_DIR="$(cd "${SCRIPT_DIR}"/../.. && pwd)"

COMMIT_EDITMSG_FILE="$BASE_DIR/$(git rev-parse --git-dir)/COMMIT_EDITMSG"
END_CONTENT=$(grep -n "^#" $COMMIT_EDITMSG_FILE | cut -d ":" -f 1 | head -n 1 | tr -d '[:space:]')

LINE_LIMIT=70

exit_with_error() {
  echo "Erro: $1"
  exit 1
}

# header
header=$(sed -n '1p' "$COMMIT_EDITMSG_FILE")

[ -n "$header" ] || exit_with_error "O cabeçalho do commit é obrigatório."

prefixos="feat|bug|fix|chore|doc"
echo "$header" | grep -qE "(^$prefixos$):" || \
	exit_with_error "O cabeçalho do commit deve começar com uma das seguintes tags: $prefixos."

echo "$header" | grep -qE "^$prefixos:\s.{1,$LINE_LIMIT}$" || \
	exit_with_error "O cabeçalho do commit deve ter o padrão 'prefixo: mensagem' e ter no máximo $LINE_LIMIT caracteres após os dois pontos."

# body
for ((i = 2; i < END_CONTENT; i++)); do
	length=$(awk "NR==${i}" $COMMIT_EDITMSG_FILE | awk '{ print length }')
	if [ "$length" -gt "$LINE_LIMIT" ]; then
			exit_with_error "O conteúdo excedeu o limite de $LINE_LIMIT caracteres na linha $i contendo $length caracteres."
	fi
done
