debug: false

server:
  port: "${PORT:8080}"
  shutdown: graceful
  servlet:
    context-path: ""
  #    context-path: "/auth"
  error:
    include-stacktrace: never
    include-message: never
    include-exception: false
    include-binding-errors: never

info:
  app:
    name: "@project.name@"
    version: "@project.version@"
    description: "@project.description@"
    profiles: "${SPRING_PROFILES_ACTIVE}"

spring:
  profiles:
    active: "${SPRING_PROFILES_ACTIVE}"
  application:
    name: "@project.artifactId@"
  main:
    banner-mode: off
  output:
    ansi:
      enabled: never
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  lifecycle:
    timeout-per-shutdown-phase: "${TIMEOUT_LIFECYCLE:5s}"
  datasource:
    url: "${DATABASE_URL}"
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  devtools:
    livereload:
      enabled: false
  flyway:
    enabled: "${FLYWAY_ENABLED:false}"
    user: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
    url: "${DATABASE_URL}"
    table: "migrations"
    driver-class-name: "org.postgresql.Driver"
    sql-migration-separator: "-"
    sql-migration-prefix: "0"
    fail-on-missing-locations: true
    locations: "classpath:migrations/prod"
    connect-retries: 3
    connect-retries-interval: "10s"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    com.bookstore: info

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - "health"
  prometheus:
    metrics:
      export:
        pushgateway:
          base-url: "${METRICS_PUSHGATEWAY}"
          enabled: true

com:
  bookstore:
    security:
      enabled: true
      jwt:
        expiration: 3600
      jwk:
        keys: "${ASYMMETRIC_KEY_PATH}"
    messaging:
      topics:
        - batata:
            enabled: true
