---
debug: true

server:
  shutdown: immediate
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always

spring:
  jpa:
    show-sql: true
  devtools:
    livereload:
      enabled: true
  flyway:
    locations: "classpath:migrations"


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    urls:
      - name: "@project.name@ - V1"
        url: "/swagger-v1.yaml"

logging:
  file:
    path: "./tmp/logs"
    name: "${START_TIME}.log"
  level:
    com.bookstore: debug
    org.springframework: debug
---
