debug: false

server:
  port: "${PORT:3000}"
  shutdown: graceful
  servlet:
    context-path: "/auth"
  error:
    include-stacktrace: never
    include-message: never
    include-exception: false
    include-binding-errors: never

spring:
  profiles:
    active: "${SPRING_PROFILES_ACTIVE}"
  main:
    banner-mode: off
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}"
    name: "${DATABASE_NAME}"
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
    driver-class-name: org.postgresql.Driver
