FROM golang:1.16-alpine as base

ENV CGO_ENABLED=0

WORKDIR /app
ADD ./go.mod ./go.sum ./
RUN go mod download && apk add make --no-cache

COPY . .
RUN make

FROM alpine

COPY --from=base /app/.env /app/.env
COPY --from=base /app/example /app/bookstore
COPY --from=base /app/src/migrations /app/migrations

CMD cd ./app && ./bookstore